# Create a new parcel [Any Auth User]
POST http://localhost:5175/api/parcel/create 
content-type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFjOTUyM2E3YmU2YTkzOTNlMmE1NzUiLCJlbWFpbCI6Im5haGlkQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzU3MDgxMzExLCJleHAiOjE3NTcxNjc3MTF9.q9yrwnQU-rKxiwWD3o1ZjlXtGIrWViGRiHpd4ZoKPfU

{
  "title":" string",
  "weight": 1,
  "height": 3,
  "width": 2,
  "receiver":{
    "phone": "01642791171",
    "email": "mdnahid6530@gmail.com",
    "address": "Noakhali"
  },
  "sender":{
    "phone": "01642791171",
    "email": "mdnahid6530@gmail.com",
    "address": "Dhaka"
  },
  "senderId": "68ac9523a7be6a9393e2a575",
  "fees": 100
}

###
# Get all parcel [Only Admin]
GET http://localhost:5175/api/parcel
content-type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFjOTUyM2E3YmU2YTkzOTNlMmE1NzUiLCJlbWFpbCI6Im5haGlkQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzU3MDgxMzExLCJleHAiOjE3NTcxNjc3MTF9.q9yrwnQU-rKxiwWD3o1ZjlXtGIrWViGRiHpd4ZoKPfU

###
# Get Parcel By Id For Traking [Any User]
GET http://localhost:5175/api/parcel/track/68aedc20f4859d105f14a1d1
content-type: application/json
Accept: application/json

###
# Cancel a Parcel [Only Sender if parcel not dispatch]
POST http://localhost:5175/api/parcel/cancel/68baef25b2c4792444cce7ba
content-type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFjOTUyM2E3YmU2YTkzOTNlMmE1NzUiLCJlbWFpbCI6Im5haGlkQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzU3MDgxMzExLCJleHAiOjE3NTcxNjc3MTF9.q9yrwnQU-rKxiwWD3o1ZjlXtGIrWViGRiHpd4ZoKPfU

{
  "message": "Parcel Cancel",
  "description": ""
}

###
# parcel status update [only admin]
POST http://localhost:5175/api/parcel/status/68aedc20f4859d105f14a1d1
content-type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFjOTUyM2E3YmU2YTkzOTNlMmE1NzUiLCJlbWFpbCI6Im5haGlkQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzU3MDgxMzExLCJleHAiOjE3NTcxNjc3MTF9.q9yrwnQU-rKxiwWD3o1ZjlXtGIrWViGRiHpd4ZoKPfU

{
  "message": "On transit",
  "description": ""
}

###
# parcel delivery update [only receiver]
POST http://localhost:5175/api/parcel/delivered/68baef25b2c4792444cce7ba
content-type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFjOTUyM2E3YmU2YTkzOTNlMmE1NzUiLCJlbWFpbCI6Im5haGlkQGdtYWlsLmNvbSIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzU3MDgxMzExLCJleHAiOjE3NTcxNjc3MTF9.q9yrwnQU-rKxiwWD3o1ZjlXtGIrWViGRiHpd4ZoKPfU

{
  "message": "Delivered",
  "description": ""
}