POST http://localhost:5175/api/user/register [Any User]
content-type: application/json
Accept: application/json

{
    "name": "ariful",
    "email": "nahid1@gmail.com",
    "phone": "01642791171",
    "password": "nahid",
    "dob": "10-11-2025"
}

###
GET http://localhost:5175/api/user/all-users [Only Admin]
content-type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFkYzg3NTQ4YTRmY2U3ZDdiYjczYTciLCJlbWFpbCI6Im5haGlkMUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTcwODA3NzAsImV4cCI6MTc1NzE2NzE3MH0.f2hqIiXhQu7jXaR-xnxpcGFkosiZ65u-fuByK8SpUMs

###
GET http://localhost:5175/api/user/profile/68ac9523a7be6a9393e2a575 [Auth User or Admin]
content-type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFkYzg3NTQ4YTRmY2U3ZDdiYjczYTciLCJlbWFpbCI6Im5haGlkMUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTcwODA3NzAsImV4cCI6MTc1NzE2NzE3MH0.f2hqIiXhQu7jXaR-xnxpcGFkosiZ65u-fuByK8SpUMs

###
GET http://localhost:5175/api/user/profile [Auth User]
content-type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGFkYzg3NTQ4YTRmY2U3ZDdiYjczYTciLCJlbWFpbCI6Im5haGlkMUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NTYyNzMxMjQsImV4cCI6MTc1NjM1OTUyNH0.VCFSAWE14J-4H--CR-3v5EnjxtOEpY796PUVESA8V9w